name: Server deployment to EC2

on:
  push:
    branches: [ master ]

jobs:   
  deploy:
    name: Deploy server to EC2
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the files
          uses: actions/checkout@v2
          
        - name: Deploy to EC2
          uses: easingthemes/ssh-deploy@main   
          with:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            REMOTE_HOST:     ${{ secrets.HOST_DNS }}
            REMOTE_USER:     ${{ secrets.USERNAME }}
            SOURCE:          server
